### ISSUE TITLE
add instructions for running app locally

### ISSUE THREAD

**Issue by ethanryan** [aravindballa/teamup#6]
Very cool app!

I'm trying to get this to work locally. I cloned this repo and ran `npm install` in both directories. I'm running `node index.js` in the server directory, and `npm start` in the web directory. It shows the app in the browser at localhost:3000, but the editing isn't collaborative, like it is on https://teamup.now.sh/.

How can I get this to work locally?

**Comment by aravindballa** [comment]
You might have missed the `.env` file. I have added detailed steps in the [CONTRIBUTING.md](https://github.com/aravindballa/teamup/blob/master/CONTRIBUTING.md) file.

Also, this isn't ready yet for use in production levels. It might break at situations if someone(person B) joins after person A has written some stuff. This was my weekend project, learning websockets.

I later discovered that Pusher's **textsync** is a great feature that we can use to achieve the same.

https://pusher.com/tutorials/collaborative-text-editor-javascript/

**Comment by aravindballa** [comment]
Feel free to reopen if you like to discuss more!
